# Base image is mariadb version 10.7.6
FROM mariadb:10.7.6

# Environment variables for the database container 
ENV MARIADB_ROOT_PASSWORD=cYmVlLqaLyLptHooVNqRusYBBgTbZRgg
ENV MARIADB_PASSWORD=cYmVlLqaLyLptHooVNqRusYBBgTbZRgg
ENV MARIADB_DATABASE=speedoku_royale_db
ENV MARIADB_USER=admin

# Exposed ports (The default port for sql database servers)
EXPOSE 3306:3306
